name: Publish "Infrastructure" NuGet Package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore Dependencies for Framework
        run: dotnet restore src/Framework/Framework.csproj

      - name: Restore Dependencies
        run: dotnet restore src/Infrastructure/Infrastructure.csproj

      - name: Build Project
        run: dotnet build src/Infrastructure/Infrastructure.csproj --configuration Release --no-restore

      - name: Pack Project
        run: dotnet pack src/Infrastructure/Infrastructure.csproj --configuration Release --no-build

      - name: Push to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push src/Infrastructure/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
